on:
  push:
    branches:
      - master
    paths:
        - 'website/**'
        - '**/website.yaml'
jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test docker
        run: docker ps
